### ISSUE TITLE
App in crash after enabling the calendar option

### ISSUE THREAD

**Issue by woody4165** [shmykelsa/AA-Tweaker#14]
Hi

I've enabled some of the options, but after enabling the calendar one, leaving 1 day, and after rebooting the phone, when entering again in the app, after clicking the "I understand" button, the app crashes and continue crashing

This is the message I get

![Screenshot_2021-03-05-16-20-30-796_com miui bugreport](https://user-images.githubusercontent.com/6501444/110135523-e85bd700-7dce-11eb-8996-e4ba6376d00f.jpg)

![Screenshot_2021-03-05-16-20-37-462_com miui bugreport](https://user-images.githubusercontent.com/6501444/110135570-f578c600-7dce-11eb-951c-3769c22e4afd.jpg)

What can I do now to let the app works again?

Thanks

**Comment by woody4165** [comment]
I've cleared all the data and then also uninstalled and reinstalled the app, but it still crashes.
What can I check to let it work again?

Thanks

**Comment by shmykelsa** [comment]
Please try [version 3.2](https://github.com/shmykelsa/AA-Tweaker/releases/tag/v3.2) and let me know if this is fixed

**Comment by woody4165** [comment]
Thanks @shmykelsa 

This version solved the app crash and now it's working again...

Choosing again Calendar option, I have to choose a value higher than 1 (is it correct?).
If I choose 2 (and maybe another value), tells me that command did not succeed and tells me to wait a minute and retry.
I did it and I see the option on, but with value 0.
So, I disabled again the option, rebooted, chosed another value (tried 2-3-4) and I get again the same message.
I see that now it's possible to send issue directly here, should I send it?

Thanks

**Comment by shmykelsa** [comment]
> Thanks @shmykelsa
> 
> This version solved the app crash and now it's working again...
> 
> Choosing again Calendar option, I have to choose a value higher than 1 (is it correct?).

Yes it is. 1 is default value so makes no sense to apply 1

> If I choose 2 (and maybe another value), tells me that command did not succeed and tells me to wait a minute and retry.

When you were doing this, did you have a green status near the button?

> I did it and I see the option on, but with value 0.
> So, I disabled again the option, rebooted, chosed another value (tried 2-3-4) and I get again the same message.

Probably it's a good idea to choose to revert everything and start from a clean base

> I see that now it's possible to send issue directly here, should I send it?
> 
> Thanks

**Comment by woody4165** [comment]
I've reverted everything, then rebooted phone, restarted with all options red, started only with calendar sat to 2 and I get same error

**Comment by shmykelsa** [comment]
When you apply the option, does the log show an error like "ERROR: Database is locked"?

**Comment by woody4165** [comment]
I get this message

![Screenshot_2021-03-07-10-19-48-463_sksa aa tweaker](https://user-images.githubusercontent.com/6501444/110235973-8d8fc000-7f33-11eb-9852-e71dfe0043d5.jpg)

And this log

```
REGISTRO:


-- Drop Triggers  --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DROP TRIGGER IF EXISTS calendar_aa_tweak;'

--  run SQL method   --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DELETE FROM Flags WHERE name="McFly__num_days_in_agenda_view";
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 0,1),2,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 1,1),2,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 2,1),2,1);
		'
	ErrorStream:
		Error: unable to open database file
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'CREATE TRIGGER calendar_aa_tweak AFTER DELETE
		ON FlagOverrides
		BEGIN
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 0,1),2,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 1,1),2,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 2,1),2,1);
		END;'
```

**Comment by shmykelsa** [comment]
Uhm, it seems like many operations are giving hard time to the database.

Is this the only tweak not working?

**Comment by woody4165** [comment]
I will try now.
Just one clarification, if I want to apply several options, should I apply them one by one and then reboot, or can I apply some or all I want all in one time?

**Comment by shmykelsa** [comment]
There should be no contraindications in doing them all in one time, however there's the risk that after doing many of them the database locks itself because of the too many operations. In that case, with the latest update, the app has been made stronger to handle this errors better and have a bit of a cooldown before making a new move.

**Comment by woody4165** [comment]
I had another crash setting up 3 options together when choosing also the "enable cards in multimedia app"
Reverting the option after a reboot, I get this log.

REGISTRO:

```

-- Reverting the hack  --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DROP TRIGGER IF EXISTS aa_media_tabs;'
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DELETE FROM FlagOverrides;'
	ErrorStream:
		Error: database is locked
```

**Comment by shmykelsa** [comment]
And other tweaks are reverted/applied fine?

**Comment by woody4165** [comment]
Also another option gives me error
The one for enabling cards in multimedia apps

```
REGISTRO:


-- Drop Triggers  --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DROP TRIGGER IF EXISTS aa_media_tabs;'

--  run SQL method   --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__tabs_media_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 0,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__media_browse_back_to_top_level_button_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 0,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__tabs_media_sticky_tab_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 0,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__tabs_media_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 1,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__media_browse_back_to_top_level_button_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 1,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__tabs_media_sticky_tab_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 1,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__tabs_media_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 2,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__media_browse_back_to_top_level_button_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 2,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__tabs_media_sticky_tab_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 2,1) ,1,1);
		'
	ErrorStream:
		Error: unable to open database file
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'CREATE TRIGGER aa_media_tabs AFTER DELETE
		ON FlagOverrides
		BEGIN
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__tabs_media_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 0,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__media_browse_back_to_top_level_button_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 0,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__tabs_media_sticky_tab_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 0,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__tabs_media_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 1,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__media_browse_back_to_top_level_button_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 1,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__tabs_media_sticky_tab_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 1,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__tabs_media_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 2,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__media_browse_back_to_top_level_button_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 2,1) ,1,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType,  name, user, boolVal, committed) VALUES ("com.google.android.projection.gearhead",0,"Tabbouleh__tabs_media_sticky_tab_enabled", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 2,1) ,1,1);
		END;'
	ErrorStream:
		Error: database is locked
```

**Comment by shmykelsa** [comment]
Seems like you are in the case of Google Play Services database not working properly, see #12 for troubleshooting

**Comment by woody4165** [comment]
On MIUI I can't uninstall updates nor uninstall Google Play Services...
Only delete cache or data

**Comment by shmykelsa** [comment]
That's really bizarre. Not even on three-dots menu?
However, you can also visit the Play Store page and uninstall updates from there. Just hit uninstall.

**Comment by woody4165** [comment]
I found the way to disable updates (removing admin right to Find My device app), and now the disable icon appeared, but it's greyed out.
Should I clear all data first?

**Comment by shmykelsa** [comment]
@woody4165 Clear all datas and skip disabling

**Comment by woody4165** [comment]
Done, activated all the ones I needs.

It's better to activate one per time and reboot.

On the calendar one I still get the error.
Also on the Multimedia cards one I had first same erro, second time the app closed itself, but after restarting the option is green, but I don't know if it's working.

**Comment by shmykelsa** [comment]
Are you able to replicate the issue and generate a bug report as done in the very first post?

**Comment by woody4165** [comment]
You mean the last error I'm receiving, on the calendar?

**Comment by shmykelsa** [comment]
@woody4165 Yes

**Comment by woody4165** [comment]
I've tried with Github credentials and with email, but in both cases it fails

**Comment by shmykelsa** [comment]
Don't worry about GitHub right now. Does a dialog like the one on the original post appear?

**Comment by woody4165** [comment]
No, that one appeared because the app was crashing, this time it's something managed by the app and the app it's not crashing this time...

**Comment by woody4165** [comment]
Hi @shmykelsa 

just downloaded the 3.2.1 and I get a similar crashing like first post in this thread.

Do you want me to send the screenshot of that log?

Thanks

**Comment by shmykelsa** [comment]
> Do you want me to send the screenshot of that log?

Yes please!

**Comment by woody4165** [comment]
Here they are.

![Screenshot_2021-03-10-13-43-40-685_com miui bugreport](https://user-images.githubusercontent.com/6501444/110631442-cf746c80-81a6-11eb-819a-79e95bdce480.jpg)

![Screenshot_2021-03-10-13-43-45-263_com miui bugreport](https://user-images.githubusercontent.com/6501444/110631462-d56a4d80-81a6-11eb-8ff2-43207e6ba791.jpg)

**Comment by shmykelsa** [comment]
I think this is happening because of the original problem. You have the calendar tweak with a null value. It's a border line situation really. 


[AA-AIO-TWEAKER--debug.zip](https://github.com/shmykelsa/AA-Tweaker/files/6115955/AA-AIO-TWEAKER--debug.zip)

This version should help. Let me know if it crashes. You should be able to set any value to the agenda now. Set it and then install the official release of AA AIO TWEAKER

**Comment by woody4165** [comment]
shuld I uninstall the actual version, install the debug version and the installa the 3.2.1 version?

Thanks

**Comment by shmykelsa** [comment]
@woody4165 Yes, correct

**Comment by woody4165** [comment]
The debug version didn't work.

I always get this grey icon.

![image](https://user-images.githubusercontent.com/6501444/110644887-d35bbb00-81b5-11eb-8289-481cac729742.png)

Instead, I have installed the 3.2 version, then I have disabled the calendar option, uninstalled the 3.2 and installed 3.2.1 and it worked this way.

Now I have set calendar to 3 days and I haven't got any error.
In an hour I will test it in car.

Thanks

**Comment by woody4165** [comment]
Even if it seems to be ok, 3 days, pressing the Calendar icon in AA, I see only 1 day.

![image](https://user-images.githubusercontent.com/6501444/110650704-0ce2f500-81bb-11eb-874c-5d27c9586970.png)

**Comment by shmykelsa** [comment]
> I have events every day in my calendar... ;-)

Could you please try to undo and redo the patch once again and send a log right here?

**Comment by shmykelsa** [comment]
Seems like you are having troubles again modifying the database, cause the log outputs 
```
 ErrorStream:
		Error: unable to open database file
```

**Comment by woody4165** [comment]
can I check something locally with some android tool (sql, terminal)?

**Comment by shmykelsa** [comment]
> can I check something locally with some android tool (sql, terminal)?

Yes. You could use an elevated shell on the phone (even via ADB) and with sqlite3 you can try to manually open/manipulate the database.

**Comment by woody4165** [comment]
Thanks, can you tell the name and path of the db and what I can try?

In the meantime, I'm preparing an old (but with Android 10 custom ROM) clean smartphone with AA and AA AIO Tweaker.
At the moment, I haven't received errors enabling the options I normally use, so later I will try to use connected in the car and using the hotspot on my normal phone (but I will loose notifications from messaging apps)...

**Comment by shmykelsa** [comment]
> Thanks, can you tell the name and path of the db and what I can try?

As for calendar tweak, try the following:

`
adb shell
su
/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db
`

Shell should have sqlite3> as output

Then

`
SELECT name,intVal, FROM FlagOverrides WHERE name="McFly__num_days_in_agenda_view";
`

You should see something like
`
McFly__num_days_in_agenda_view, 3
McFly__num_days_in_agenda_view, 3
McFly__num_days_in_agenda_view, 3
`

Then let's check if the trigger was created successfully
`
SELECT * FROM sqlite_master WHERE name="calendar_aa_tweak";
`

**Comment by woody4165** [comment]
I've used an android app to access the `phenotype.db`

the first SELECT produce no data

I don't find the table `sqlite_master`

**Comment by shmykelsa** [comment]
> the first SELECT produce no data

Okay something has gone wrong with AA AIO TWEAKER's agenda tweak 

> I don't find the table sqlite_master

Normally it's not displayed, hence why I suggested to do it via shell

Anyways, try to undo and re-do the agenda tweak with this version. 

[AA-AIO-TWEAKER-debug.zip](https://github.com/shmykelsa/AA-Tweaker/files/6121791/AA-AIO-TWEAKER-debug.zip)

**Comment by woody4165** [comment]
Here is the output from the terminal

sqlite>                                               a
sqlite> SELECT name,intVal FROM FlagOverrides WHERE name="McFly__num_days_in_agenda_view";
sqlite> SELECT * FROM sqlite_master WHERE name="calendar_aa_tweak";
trigger|calendar_aa_tweak|FlagOverrides|0|CREATE TRIGGER calendar_aa_tweak AFTER DELETE
ON FlagOverrides
BEGIN
INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 0,1),3,1);
INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 1,1),3,1);
INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 2,1),3,1);
END
sqlite>

**Comment by shmykelsa** [comment]
Okay. Try out the new version I've attached.

**Comment by woody4165** [comment]
> > the first SELECT produce no data
> 
> Okay something has gone wrong with AA AIO TWEAKER's agenda tweak
> 
> > I don't find the table sqlite_master
> 
> Normally it's not displayed, hence why I suggested to do it via shell
> 
> Anyways, try to undo and re-do the agenda tweak with this version.
> 
> [AA-AIO-TWEAKER-debug.zip](https://github.com/shmykelsa/AA-Tweaker/files/6121791/AA-AIO-TWEAKER-debug.zip)

With this version, the app crashes

java.lang.RuntimeException: Unable to start activity ComponentInfo{sksa.aa.tweaker/sksa.aa.tweaker.MainActivity}: java.lang.NumberFormatException: For input string: ""
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7565)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:627)
	at java.lang.Integer.parseInt(Integer.java:650)
	at sksa.aa.tweaker.MainActivity.onCreate(MainActivity.java:1117)
	at android.app.Activity.performCreate(Activity.java:7916)
	at android.app.Activity.performCreate(Activity.java:7903)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3288)
	... 11 more

**Comment by woody4165** [comment]
I tried on the other phone the debug version, and it runs ok.
Now I try to reset all the settings in the 3.2.1. app and start from scratch with the debug version

**Comment by woody4165** [comment]
Now I'm blocked, I try the debug version, 3.2.1 and 3.1 (that was working yesterday, while the newer and debug versions were crashing) and the app always crashes...

What can I do now ?

Thanks

**Comment by shmykelsa** [comment]
Does it crash past the initial warning screen?

**Comment by woody4165** [comment]
Yes, after 5 seconds countdown

**Comment by shmykelsa** [comment]
Are you able to reproduce a bug report like in the original post?

**Comment by woody4165** [comment]
Here it is.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{sksa.aa.tweaker/sksa.aa.tweaker.MainActivity}: java.lang.NumberFormatException: For input string: ""
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7565)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:627)
	at java.lang.Integer.parseInt(Integer.java:650)
	at sksa.aa.tweaker.MainActivity.onCreate(Unknown Source:2251)
	at android.app.Activity.performCreate(Activity.java:7916)
	at android.app.Activity.performCreate(Activity.java:7903)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3288)
	... 11 more
```

**Comment by woody4165** [comment]
I've tried the test phone and the Calendar option is working, but not as I was expecting. 
It's a list of events without any divider between different days and the heading remains on the first day with events.

But now, my issue is try to solve the crash issue.
I've also cleared alla app data and reinstalled the latest version and also the latest debug version you sent me, but still the same....

In the next days or week, if I have time, I will try to switch from stock MIUI 12 to Resurrection Remix, on my Poco X3

Thanks

**Comment by shmykelsa** [comment]
> I've tried the test phone and the Calendar option is working, but not as I was expecting.
> It's a list of events without any divider between different days and the heading remains on the first day with events.

That's clearly mentioned in the built-in tutorial

> But now, my issue is try to solve the crash issue.
> I've also cleared alla app data and reinstalled the latest version and also the latest debug version you sent me, but still the same....

Try this: uninstall actual version, try [version 2.6](https://github.com/shmykelsa/AA-Tweaker/releases/tag/v2.6), if status is green near the agenda tweak, deactivate the tweak. Select a day and do the tweak. Try then to install latest version.

> In the next days or week, if I have time, I will try to switch from stock MIUI 12 to Resurrection Remix, on my Poco X3
> 
> Thanks

**Comment by woody4165** [comment]
> That's clearly mentioned in the built-in tutorial
> 

ok, thanks, I haven't checked this before.


> Try this: uninstall actual version, try [version 2.6](https://github.com/shmykelsa/AA-Tweaker/releases/tag/v2.6), if status is green near the agenda tweak, deactivate the tweak. Select a day and do the tweak. Try then to install latest version.
Done and now crash has ended and I check that I had no error messages during uncheck and check calendar option in 2.6.0

Now I've reinstalled 3.2.1 and calendar option is green but with 0 day .

What do you suggest?
Uncheck it, reboot, check it again with x days (checking that I have no errors) and reboot again?
Or leave it like it is ?

Thanks!

**Comment by shmykelsa** [comment]
That's a visual bug that will be fixed in next version

**Comment by shmykelsa** [comment]
@woody4165 could you please report the working status on latest version?

**Comment by woody4165** [comment]
Hi

I've just tested removing the calendar option (since was showing 1 day, but it's set to 3.

This is reverting the hack

-- Reverting the hack  --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DROP TRIGGER IF EXISTS calendar_aa_tweak;'
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DELETE FROM FlagOverrides;'
	ErrorStream:
		Error: unable to open database file


And, after a reboot, this is installing the hack

-- Drop Triggers  --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DROP TRIGGER IF EXISTS calendar_aa_tweak;'
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DELETE FROM Flags WHERE name="McFly__num_days_in_agenda_view";
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 0,1),3,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 1,1),3,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 2,1),3,1);
		'
	ErrorStream:
		Error: unable to open database file

--  run SQL method   --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'CREATE TRIGGER calendar_aa_tweak AFTER DELETE
		ON FlagOverrides
		BEGIN
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 0,1),3,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 1,1),3,1);
		INSERT OR REPLACE INTO FlagOverrides (packageName, flagType, name, user, intVal, committed) VALUES ("com.google.android.projection.gearhead",0,"McFly__num_days_in_agenda_view", (SELECT DISTINCT user FROM Flags WHERE user != ""LIMIT 2,1),3,1);
		END;'

And now it shows it good.
I've to test in AA..

![IMG_20210319_130308](https://user-images.githubusercontent.com/6501444/111777966-47801800-88b4-11eb-9ae1-ada7506ccbe4.jpg)
